name: Node.js Package
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - id: publish
        uses: JS-DevTools/npm-publish@v2
        run: echo ${{ secrets.npm_token }}
        with:
          token: ${{ secrets.npm_token }}
  
